### ISSUE TITLE
Failed to Install Plugin

### ISSUE THREAD

**Issue by dflvunoooooo** [Saiyato/volumio-snapclient-plugin#10]
I am struggeling to install the plugin. I followed the instructions here [https://github.com/Saiyato/volumio-lastfm-plugin/issues/19#issuecomment-1002618076](https://github.com/Saiyato/volumio-lastfm-plugin/issues/19#issuecomment-1002618076) but changed to `./volumio_install_from_zip.sh Saiyato volumio-snapclient-plugin`.

After confirming the plugin installation with a y, the output is as followed:

```
 ================================ WARNING ====================================
 
This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.
 
 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
nloading plugin at http://127.0.0.1:3000/plugin-serve/snapclient.zip
Progress: 30
Status :Creating install location
Creating install location
Progress: 40
Status :Unpacking plugin
Unpacking plugin
Progress: 45
Status :Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Progress: 50
Status :Checking for duplicate plugin
Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Installing necessary utilities
Progress: 70
Status :Es ist ein Fehler während der Plugin-Installation aufgetreten Error
Installing SnapClient and dependencies...
Progress: 70
Status :Es ist ein Fehler während der Plugin-Installation aufgetreten Error
Installing SnapClient and dependencies...
Progress: 70
Status :Es ist ein Fehler während der Plugin-Installation aufgetreten Error
Installing SnapClient and dependencies...
Progress: 70
Status :Es ist ein Fehler während der Plugin-Installation aufgetreten Error
Installing SnapClient and dependencies...
Progress: 70
Status :Es ist ein Fehler während der Plugin-Installation aufgetreten Error
Installing SnapClient and dependencies...
Progress: 0
Status :An error occurred while installing the plugin Error
An error occurred while installing the plugin Error
Failed to Install Plugin
Plugin installed successfully!
```

If I try to install it manually, by downloading, extracting, removing zip and entering directory I get the following error:

```
 ================================ WARNING ====================================
 
This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.
 
 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/snapclient.zip' is not a directory
(node:2027) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/mv *.zip /tmp/plugins/snapclient.zip
/bin/mv: target '/tmp/plugins/snapclient.zip' is not a directory

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /volumio/pluginhelper.js:778:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2027) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have no cloe what I do wrong. Has anybody an idea?

Edit: Installation of snapserver is working.

**Comment by dflvunoooooo** [comment]
Never mind, it did work some time bevore. The plugin is there and I can use it.
