### ISSUE TITLE
plugin is failing to start

### ISSUE THREAD

**Issue by Hendrick42** [Saiyato/volumio-snapclient-plugin#8]
Hi, the installation of the plugin from the .zip file succeeded on Volumio which is a fresh install on a raspberry pi zero Volumio-3.251-2022-03-31-pi.zip. (not sure anymore if I had to sudo ln -s /usr/bin/npm /usr/local/bin/npm)

When going to the "installed plugin" section Snapclient 1.0.6 is listed, but disabled - I have no myvolumio account and have to close the "Please login" dialog.

When trying to enable the Plugin a red box in the upper right corner shows me:  
```
snapclient Plugin
This plugin is failing to start. Please install updated version, or contact plugin developer
```

When using the Live log its more verbose:
```
info: Enabling plugin snapclient
info: Loading plugin "snapclient"...
error: !!!! WARNING !!!!
error: The plugin audio_interface/snapclient failed to load, setting it to stopped. Error: Error: Cannot find module 'kew'
Require stack:
- /data/plugins/audio_interface/snapclient/index.js
- /volumio/app/pluginmanager.js
- /volumio/app/index.js
- /volumio/index.js
error: Stack trace: Error: Cannot find module 'kew'
Require stack:
- /data/plugins/audio_interface/snapclient/index.js
- /volumio/app/pluginmanager.js
- /volumio/app/index.js
- /volumio/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object. (/data/plugins/audio_interface/snapclient/index.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:235:29)
    at Promise._successFn (/volumio/app/pluginmanager.js:1841:19)
    at nextTickCallback (/volumio/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: !!!! WARNING !!!!
info: Done.
```

The File `/volumio/node_modules/kew/kew.js` does exists. I also uninstalled it and used the `npm -i` command before the `volumio plugin install` with the same result.

i have no clue how to handle the javascript, so I am stuck right now..

**Comment by Hendrick42** [comment]
My Snapcast Android app showed the volumiozero client as seen yesterday. So i did try to install it again. Got the same error messages. 
But after some reboots it was showing "active" and could be configured.

I am not closing this issue - cause for me this does not seem like the way to go?!

**Comment by Saiyato** [comment]
Sounds like a manual installation issue, this is very specific. You're better off using the script I prepare to 'lazy' install plugins :wink: You can find it here: github.com/saiyato/volumio-plugin-helper

Also, you'll probably have issues with playback from the snapserver plugin, unless you install from the development branch (updated tonight)

**Comment by Saiyato** [comment]
Those are the first and second arguments for the script; so ./script.sh ARGUMENT1 ARGUMENT2

**Comment by Saiyato** [comment]
As mentioned in the other repo, the server and client have been revamped to support the AAMPP architecture. This is still alpha, but I will continue working on some features to hit BETA. Once BETA finishes, I will publish to the volumio plugin store for easy installation.
